services:
  api-solid-03-pg:
    image: bitnami/postgresql
    container_name: expenses-db
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=expenses_db